# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jackson/hajime/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jackson/hajime

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jackson/hajime/CMakeFiles /home/jackson/hajime//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jackson/hajime/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hajime

# Build rule for target.
hajime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hajime
.PHONY : hajime

# fast build rule for target.
hajime/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/build
.PHONY : hajime/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f zlib/CMakeFiles/zlib.dir/build.make zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) $(MAKESILENT) -f zlib/CMakeFiles/zlibstatic.dir/build.make zlib/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f zlib/CMakeFiles/example.dir/build.make zlib/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named minigzip

# Build rule for target.
minigzip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minigzip
.PHONY : minigzip

# fast build rule for target.
minigzip/fast:
	$(MAKE) $(MAKESILENT) -f zlib/CMakeFiles/minigzip.dir/build.make zlib/CMakeFiles/minigzip.dir/build
.PHONY : minigzip/fast

#=============================================================================
# Target rules for targets named example64

# Build rule for target.
example64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example64
.PHONY : example64

# fast build rule for target.
example64/fast:
	$(MAKE) $(MAKESILENT) -f zlib/CMakeFiles/example64.dir/build.make zlib/CMakeFiles/example64.dir/build
.PHONY : example64/fast

#=============================================================================
# Target rules for targets named minigzip64

# Build rule for target.
minigzip64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minigzip64
.PHONY : minigzip64

# fast build rule for target.
minigzip64/fast:
	$(MAKE) $(MAKESILENT) -f zlib/CMakeFiles/minigzip64.dir/build.make zlib/CMakeFiles/minigzip64.dir/build
.PHONY : minigzip64/fast

constants.o: constants.cpp.o
.PHONY : constants.o

# target to build an object file
constants.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/constants.cpp.o
.PHONY : constants.cpp.o

constants.i: constants.cpp.i
.PHONY : constants.i

# target to preprocess a source file
constants.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/constants.cpp.i
.PHONY : constants.cpp.i

constants.s: constants.cpp.s
.PHONY : constants.s

# target to generate assembly for a file
constants.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/constants.cpp.s
.PHONY : constants.cpp.s

deduce.o: deduce.cpp.o
.PHONY : deduce.o

# target to build an object file
deduce.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/deduce.cpp.o
.PHONY : deduce.cpp.o

deduce.i: deduce.cpp.i
.PHONY : deduce.i

# target to preprocess a source file
deduce.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/deduce.cpp.i
.PHONY : deduce.cpp.i

deduce.s: deduce.cpp.s
.PHONY : deduce.s

# target to generate assembly for a file
deduce.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/deduce.cpp.s
.PHONY : deduce.cpp.s

getvarsfromfile.o: getvarsfromfile.cpp.o
.PHONY : getvarsfromfile.o

# target to build an object file
getvarsfromfile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/getvarsfromfile.cpp.o
.PHONY : getvarsfromfile.cpp.o

getvarsfromfile.i: getvarsfromfile.cpp.i
.PHONY : getvarsfromfile.i

# target to preprocess a source file
getvarsfromfile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/getvarsfromfile.cpp.i
.PHONY : getvarsfromfile.cpp.i

getvarsfromfile.s: getvarsfromfile.cpp.s
.PHONY : getvarsfromfile.s

# target to generate assembly for a file
getvarsfromfile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/getvarsfromfile.cpp.s
.PHONY : getvarsfromfile.cpp.s

hajime.o: hajime.cpp.o
.PHONY : hajime.o

# target to build an object file
hajime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/hajime.cpp.o
.PHONY : hajime.cpp.o

hajime.i: hajime.cpp.i
.PHONY : hajime.i

# target to preprocess a source file
hajime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/hajime.cpp.i
.PHONY : hajime.cpp.i

hajime.s: hajime.cpp.s
.PHONY : hajime.s

# target to generate assembly for a file
hajime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/hajime.cpp.s
.PHONY : hajime.cpp.s

httplib/httplib.o: httplib/httplib.cpp.o
.PHONY : httplib/httplib.o

# target to build an object file
httplib/httplib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/httplib/httplib.cpp.o
.PHONY : httplib/httplib.cpp.o

httplib/httplib.i: httplib/httplib.cpp.i
.PHONY : httplib/httplib.i

# target to preprocess a source file
httplib/httplib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/httplib/httplib.cpp.i
.PHONY : httplib/httplib.cpp.i

httplib/httplib.s: httplib/httplib.cpp.s
.PHONY : httplib/httplib.s

# target to generate assembly for a file
httplib/httplib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/httplib/httplib.cpp.s
.PHONY : httplib/httplib.cpp.s

installer.o: installer.cpp.o
.PHONY : installer.o

# target to build an object file
installer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/installer.cpp.o
.PHONY : installer.cpp.o

installer.i: installer.cpp.i
.PHONY : installer.i

# target to preprocess a source file
installer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/installer.cpp.i
.PHONY : installer.cpp.i

installer.s: installer.cpp.s
.PHONY : installer.s

# target to generate assembly for a file
installer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/installer.cpp.s
.PHONY : installer.cpp.s

languages.o: languages.cpp.o
.PHONY : languages.o

# target to build an object file
languages.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/languages.cpp.o
.PHONY : languages.cpp.o

languages.i: languages.cpp.i
.PHONY : languages.i

# target to preprocess a source file
languages.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/languages.cpp.i
.PHONY : languages.cpp.i

languages.s: languages.cpp.s
.PHONY : languages.s

# target to generate assembly for a file
languages.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/languages.cpp.s
.PHONY : languages.cpp.s

output.o: output.cpp.o
.PHONY : output.o

# target to build an object file
output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/output.cpp.o
.PHONY : output.cpp.o

output.i: output.cpp.i
.PHONY : output.i

# target to preprocess a source file
output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/output.cpp.i
.PHONY : output.cpp.i

output.s: output.cpp.s
.PHONY : output.s

# target to generate assembly for a file
output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/output.cpp.s
.PHONY : output.cpp.s

server.o: server.cpp.o
.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i
.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s
.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server.cpp.s
.PHONY : server.cpp.s

server_features.o: server_features.cpp.o
.PHONY : server_features.o

# target to build an object file
server_features.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server_features.cpp.o
.PHONY : server_features.cpp.o

server_features.i: server_features.cpp.i
.PHONY : server_features.i

# target to preprocess a source file
server_features.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server_features.cpp.i
.PHONY : server_features.cpp.i

server_features.s: server_features.cpp.s
.PHONY : server_features.s

# target to generate assembly for a file
server_features.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server_features.cpp.s
.PHONY : server_features.cpp.s

server_performance.o: server_performance.cpp.o
.PHONY : server_performance.o

# target to build an object file
server_performance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server_performance.cpp.o
.PHONY : server_performance.cpp.o

server_performance.i: server_performance.cpp.i
.PHONY : server_performance.i

# target to preprocess a source file
server_performance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server_performance.cpp.i
.PHONY : server_performance.cpp.i

server_performance.s: server_performance.cpp.s
.PHONY : server_performance.s

# target to generate assembly for a file
server_performance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server_performance.cpp.s
.PHONY : server_performance.cpp.s

server_performance_counters.o: server_performance_counters.cpp.o
.PHONY : server_performance_counters.o

# target to build an object file
server_performance_counters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server_performance_counters.cpp.o
.PHONY : server_performance_counters.cpp.o

server_performance_counters.i: server_performance_counters.cpp.i
.PHONY : server_performance_counters.i

# target to preprocess a source file
server_performance_counters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server_performance_counters.cpp.i
.PHONY : server_performance_counters.cpp.i

server_performance_counters.s: server_performance_counters.cpp.s
.PHONY : server_performance_counters.s

# target to generate assembly for a file
server_performance_counters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/server_performance_counters.cpp.s
.PHONY : server_performance_counters.cpp.s

wizard.o: wizard.cpp.o
.PHONY : wizard.o

# target to build an object file
wizard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/wizard.cpp.o
.PHONY : wizard.cpp.o

wizard.i: wizard.cpp.i
.PHONY : wizard.i

# target to preprocess a source file
wizard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/wizard.cpp.i
.PHONY : wizard.cpp.i

wizard.s: wizard.cpp.s
.PHONY : wizard.s

# target to generate assembly for a file
wizard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hajime.dir/build.make CMakeFiles/hajime.dir/wizard.cpp.s
.PHONY : wizard.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... example"
	@echo "... example64"
	@echo "... hajime"
	@echo "... minigzip"
	@echo "... minigzip64"
	@echo "... zlib"
	@echo "... zlibstatic"
	@echo "... constants.o"
	@echo "... constants.i"
	@echo "... constants.s"
	@echo "... deduce.o"
	@echo "... deduce.i"
	@echo "... deduce.s"
	@echo "... getvarsfromfile.o"
	@echo "... getvarsfromfile.i"
	@echo "... getvarsfromfile.s"
	@echo "... hajime.o"
	@echo "... hajime.i"
	@echo "... hajime.s"
	@echo "... httplib/httplib.o"
	@echo "... httplib/httplib.i"
	@echo "... httplib/httplib.s"
	@echo "... installer.o"
	@echo "... installer.i"
	@echo "... installer.s"
	@echo "... languages.o"
	@echo "... languages.i"
	@echo "... languages.s"
	@echo "... output.o"
	@echo "... output.i"
	@echo "... output.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... server_features.o"
	@echo "... server_features.i"
	@echo "... server_features.s"
	@echo "... server_performance.o"
	@echo "... server_performance.i"
	@echo "... server_performance.s"
	@echo "... server_performance_counters.o"
	@echo "... server_performance_counters.i"
	@echo "... server_performance_counters.s"
	@echo "... wizard.o"
	@echo "... wizard.i"
	@echo "... wizard.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

