help.push_back("\033[1m¡Bienvenido a Hajime, el programa definitivo para el encendido de servidores de Minecraft!\033[0m");
help.push_back("Esta versión de Hajime fue compilada esta fecha: " __DATE__ ".");
help.push_back("\033[1m\033[32mUso:\033[0m ");
help.push_back(" [los siguientes indicadores]");
help.push_back("\033[1m-f \033[3marchivo\033[0m o \033[1m--server-file \033[3marchivo \033[0m\033[1m|\033[0m Especificar un archivo para usar.");
help.push_back("\033[1m-h \033[0mo\033[1m --help |\033[0m Mostrar este mensaje de ayuda.");
help.push_back("\033[1m-hf \033[1m\033[3marchivo \033[0mo\033[1m --hajime-file\033[0m \033[1m\033[3marchivo \033[0m\033[1m|\033[0m Especificar el archivo de configuración que usa Hajime.");
help.push_back("\033[1m-s  \033[0mu\033[1m --install-server \033[1m|\033[0m Crear un archivo estándar para la configuración de un servidor.");
help.push_back("\033[1m-ih \033[1m\033[3marchivo \033[0mu\033[1m --install-hajime-config \033[1m\033[3marchivo \033[0m\033[1m|\033[0m Instalar el archivo estándar que usa Hajime.");
help.push_back("\033[1m-S  \033[0mu\033[1m --install-service \033[1m|\033[0m Instalar un archivo de encendido para empezar Hajime.");
help.push_back("\033[1m-ss \033[0mu\033[1m --install-servers-file \033[1m|\033[0m Instalar un archivo para apuntar los servidores.");
help.push_back("\033[1m-v \033[0mo\033[1m --verbose \033[1m|\033[0m Activar los registros verbosos.");
help.push_back("\033[1m-i \033[0mu\033[1m --install-hajime \033[1m|\033[0m Procesar el asistente de instalación de Hajime.");
help.push_back("\033[1m-m \033[0mo\033[1m --monochrome \033[0mor\033[1m --no-colors \033[1m|\033[0m Desactivar los colores de los registros.");
help.push_back("\033[1m-d \033[0mo\033[1m --debug \033[1m|\033[0m Activar los registros de depurar.");
help.push_back("\033[1m-l \033[0mo\033[1m --language \033[1m|\033[0m Escoger el lenguaje que usará Hajime.");
help.push_back("\033[1m-np \033[0mo\033[1m --no-pauses \033[1m|\033[0m Desactivar las pausas artificiales.");
help.push_back("\033[1m-tc \033[0mo\033[1m --thread-colors \033[1m|\033[0m Fijar los colores por la identificación de los threads en lugar del tipo del mensaje.");
help.push_back("\033[1m-it \033[0mo\033[1m --show-info-type \033[1m|\033[0m Fijar el tipo de información en los registros explícitamente.");
help.push_back("\033[1m\033[32m¿Necesitas más ayuda?\033[0m Únete nuestro grupo de Discord aquí: https://discord.gg/J6asnc3pEG");
eno.NotPermitted = "No es permitido. ¿Es correcto el aparato?";
eno.NoFileOrDir = "No hay ese tipo de archivo ni directorio.";
eno.PermissionDenied = "No tiene el permiso necesario. ¿Estás ejecutando Hajime como el usuario root?";
eno.InOut = "Error de entra/salida. ¿Está OK el lector?";
eno.Memory = "No hay suficiente memoria.";
eno.Unavailable = "El recurso no está disponible.";
eno.Address = "La dirección está mala.";
eno.BlockDev = "No es un dispositivo de bloques. ¿Estás accediendo un dispositivo de almacenamiento masivo?";
eno.Busy = "Está ocupado. ¿Se está accediendo ahora mismo?";
prefix.VInfo = "Info";
prefix.VError = "Error";
prefix.VWarning = "Aviso";
prefix.VDebug = "Depurar";
#if defined(_WIN64) || defined (_WIN32)
prefix.VQuestion = "Pregunta"; //Windows doesn't support 24 bit terminal colors
#else
prefix.VQuestion = "Pregunta";
#endif
error.NotEnoughArgs = "No hay suficientes argumentos";
error.ConfDoesNotExist1 = "¡El archivo de configuración ";
error.ConfDoesNotExist2 = " no existe!";
error.NoHajimeConfig = "Archivo estándar de configuation de Hajime no existe";
error.StartupServiceWindowsAdmin = "Hay que ejecutar Hajime como el administrador para que instale el servicio de encendido.";
error.SystemdRoot = "Hay que ejecutar Hajime como el user root para que instale un servicio de systemd.";
error.NoSystemd = "Parece que no haya ningún sistema de encendido compatible";
error.ServersFilePresent = "¡Hay un archivo de servidor ya!";
error.ServerFileNotPresent1 = "El archivo de configuración para el servidor (";
error.ServerFileNotPresent2 = ") no existe";
error.ServersFileNotCreated = "No se creyó el archivo de configuración para servidores";
error.CouldntSetPath = "No pudo cambiar la dirección";
error.Generic = "Ocurrió un error desconocido.";
error.MethodNotValid = "El método no es válido";
error.CreatingDirectory = "Error al crear el directorio";
error.FilesInPath = "Hay archivos en la dirección";
error.NoServersFile = "No hay nada archivo de servidor";
error.Mount = "Ocurrió un error, pero Hajime tratará a continuar. El error: ";
error.Code = "Número del error: ";
error.HajFileNotMade = "No se creyó el archivo de configuración para Hajime";
error.ServerConfNotCreated = "No se creyó el archivo de configuración para el servidor";
error.OptionNotAvailable = "Disculpa, esta opción no todavía está disponible.";
error.InvalidServerNumber = "Número de servidor inválido";
error.ServerSelectionInvalid = "Selección de servidor inválida";
error.DoesntSupportWindows = "Esta característica no es compatible con Windows";
error.InvalidCommand = "Comando inválido; lista de comandos válidos:";
error.InvalidHajCommand1 = "term, t [servidor] | conectar al servidor";
error.InvalidServerCommand1 = ".d - desconectar del servidor";
warning.FoundSysvinitService = "Encontró un servicio de sysVinit instalado ya";
warning.FoundSystemdService = "Encontró un servicio de systemd instalado ya";
warning.IsRunningFalse = "isRunning está falso ahora";
warning.TestingWindowsSupport = "¡Está probando ser compatible con Windows!";
warning.LaunchdServPresent = "Encontró un servicio de launchd";
warning.FoundServerConf = "¡Hay un archivo de configuración aquí!";
warning.FoundServerConfPlusFile = "Hay un archivo de servidor con el nombre ";
warning.FoundHajConf = "¡Hay un archivo de configuración para Hajime aquí!";
question.MakeLaunchdServ = "¿Te gustaría crear un archivo de configuración para launchd de todas maneras?";
question.Prompt = "[s/n]";
question.MakeHajimeConfig = "Parece que no haya un archivo de configuración para Hajime. ¿Te gustaría crearlo?";
question.MakeServerConfig = "¿Te gustaría crear un nuevo archivo de configuración de todas formas?";
question.MakeNewSysvinitService = "¿Te gustaría instalar un nuevo servicio de sysVinit?";
question.WizardServersFile = "¿Te gustaría instalarlo ahora?";
question.WizardServerFile = "¿Te gustaría hacer el archivo del servidor ahora?";
question.WizardStartupService = "¿Te gustaría instalar un servicio de encendido ahora?";
question.SysvinitUser = "Por favor, pon el USER que usará Hajime. ";
question.SysvinitGroup = "Por favor, pon el GRUPO del user. ";
question.DoSetupInstaller = "Parece que no has ejecutado Hajime ya. ¿Te gustaría hacer el asistente de instalación?";
question.UseFlags = "¿Te gustaría usar indicadores de Java ya hechos con el servidor?";
question.InstallNewOne = "¿Te gustaría instalarlo?";
question.InstallNewOneAgain = "¿Te gustaría instalarlo otra vez?";
question.CreateAnotherServerFile = "¿Te gustaría crear otro archivo de servidor?";
question.StartHajime = "¿Te gustía ejecutar Hajime ahora? Pon \"n\" para exitar.";
question.ApplyConfigToServerFile = "¿Te gustaría hacer una configuración para el archivo del servidor?";
question.UseDefaultServerFile1 = "¿Te gustaría usar el archivo estándar del servidor (";
question.UseDefaultServerFile2 = ") u otra cosa?";
question.EnterNewServerFile = "Pon un archivo nuevo para el servidor: ";
question.EnterCustomFlags = "Pon tus indicadores a medidas: ";
option.MakeServerFileManually = "Poner un archivo de servidor manualmente";
option.DoManually = "Hacerlo manualmente";
option.EnterManually = "Ponerlo manualmente";
option.LetHajimeDeduce = "Dejar Hajime deducirlo para mí";
option.SkipStep = "Faltar a este paso";
option.UseDefault = "Usar el estándar";
option.ChooseOptionBelow = "Elige una opción abaja.";
option.YourChoice = "Tu selección: ";
option.AttendedInstallation = "Hacer una instalación con supervisión";
option.UnattendedInstallation = "Hacer una instalación sin supervisión";
option.SkipSetup = "Faltar a esta instalación";
option.AikarFlags = "Usar Aikar's Flags";
option.HillttyFlags = "Usar Hilltty's Flags";
option.FroggeMCFlags = "Usar FroggeMC's ZGC Flags";
option.BasicZGCFlags = "Usar indicadores básicos de ZGC";
option.CustomFlags = "Usar indicadores a medidas";
info.InstallingSysvinit = "Se está instalando el servicio de sysVinit";
info.InstallingNewSysvinit = "Se está instalando un nuevo servicio de sysVinit";
info.InstalledSysvinit = "Instaló el servicio de sysVinit en /etc/init.d/hajime.sh";
info.CreatedServerConfig1 = "El archivo de configuración (";
info.CreatedServerConfig2 = ") se ha creado";
info.AbortedSysvinit = "Se terminó la instalación de un servicio de sysVinit";
info.NoLogFile = "No hay nada archivo de registros; está poniendo los registros al terminal.";
info.ReadingServerSettings = "Está leyendo las configuraciones del servidor...";
info.ServerFile = "Archivo del servidor: ";
info.ServerPath = "Dirección del servidor: ";
info.ServerCommand = "Comando del servidor: ";
info.ServerMethod =  "Método del encendido del servidor: ";
info.ServerDevice = "Dispositivo: ";
info.ServerDebug = "Número de depurar: ";
info.ServerIsRunning = "¡Está ejecutando el programa!";
info.TryingToStartProgram = "Está tratando a ejecutar el programa";
info.StartingServer = "¡Está ejecutando el servidor!";
info.ServerStartCompleted = "Está completado el encendido del servidor";
info.POSIXdriveMount = "Hay que montar con los sistemas de POSIX solamente";
info.TryingFilesystem1 = "Está probando el sistema de archivo ";
info.TryingFilesystem2 = "";
info.TryingMount = "Está tratando a montar";
info.CreatingDirectory = "Está creando un nuevo directorio";
info.NoMount = "No hay nada aparato; ¡no tiene que montar!";
info.DeviceMounted = "¡Está montado el aparato!";
info.wizard.HajimeFile = "Empezamos hacer el archivo que usará Hajime para las configuraciones básicas.";
info.wizard.ServersFile = "Entonces, necesitamos instalar el \"archivo de servidores,\" donde Hajime buscará los servidores.";
info.wizard.ServerFile = "Necesitamos un archivo de servidor para las configuraciones de un servidor.";
info.wizard.StartupService = "Finalmente, necesitamos ejecutar Hajime cuando enciende el SO.";
info.wizard.Complete = "¡Está completada la configuración!";
info.wizard.NextStepServerFile1 = "El Próximo Paso: Poner las configuraciones del servidor en ";
info.InstallingDefServConf = "Está instalando un archivo estándar para el servidor de configuración en ";
info.InstallingNewServConf = "Está instalando un nuevo archivo de configuración para el servidor con el nombre ";
info.InstallingDefHajConf = "Está instalando un archivo estándar de configuración para Hajime ";
info.CheckingExistingFile = "Está buscando archivos actuales...";
info.HajConfigMade1 = "¡El archivo de configuración para Hajime (";
info.HajConfigMade2 = ") se ha creado!";
info.InstallingWStartServ = "Está instalando un servicio de encendido para Windows";
info.TipAdministrator = "Consejo: Haz clic derecho el ícono del terminal y haz clic \"Run as administrator\"";
info.InstallingLaunchdServ = "Está instalando un servicio de encendido para launchd";
info.InstallingNewLaunchdServ = "Está instalando un nuevo servicio de encendido para launchd";
info.InstalledLaunchServ = "Instaló un servicio para launchd";
info.AbortedLaunchServ = "Terminó la instalación del servicio para launchd";
info.InstallingServersFile = "Está instalando el archivo de servidores en ";
info.CheckingExistingServersFile = "Está buscando archivos actuales de servidores...";
info.MadeServersFile = "¡Instaló el archivo de servidores!";
info.MakingSystemdServ = "Está haciendo un servicio de systemd en ";
info.EnterNewNameForServer1 = "Elige un nuevo nombre para el próximo arhcivo del servidor (el anterior fue ";
info.EnterCommand = "Pon un comando...";
debug.HajDefConfNoExist1 = "Intentó leer las configuraciones de ";
debug.HajDefConfNoExist2 = " pero el archivo no existe";
debug.ReadingReadsettings = "Está leyendo las configuraciones en readSettings()";
debug.ReadReadsettings = "Leyó las configuraciones con éxito del archivo ";
debug.flag.VecInFor = "flagVector[0] en el bucle For =";
debug.flag.VecOutFor = "flagVector[0] afuera el bucle For =";
debug.UsingOldMethod = "Está usando el método viejo";
debug.UsingNewMethod = "Está usando el nuevo método";
debug.ValidatingSettings = "Está verificando las configuraciones del servidor";
server.restart.minutes5 = "§6[Hajime]§f Este servidor reiniciará en §b5 §fminutos";
server.restart.minutes15 = "§6[Hajime]§f Este servidor reiniciará en §b15 §fminutos";
server.command.hajime.regex = ".hajime";
server.command.hajime.output = "[\"§6[Hajime] §fEste servidor está usando \",{\"text\":\"Hajime 0.1.9\",\"underlined\":true,\"color\":\"aqua\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https:\/\/hajime.sh\"}}]";
server.command.time.regex = ".tiempo";
server.command.time.output = "tellraw @a \"§6[Hajime]§f El tiempo local de este servidor es §b";
server.command.help.regex = ".a(yuda)";
server.command.help.output1 = "§6[Hajime]§f Posa el cursor sobre un comando para ver la acción.";
server.command.help.output2 = "[{\"text\":\".lanzar, \",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\"§bLanzar una moneda.\"},\"clickEvent\":{\"action\":\"suggest_command\",\"value\":\".lanzar\"}},{\"text\":\".dado, \",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\"§bTirar un dado.\"},\"clickEvent\":{\"action\":\"suggest_command\",\"value\":\".dado\"}},{\"text\":\".discord, \",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\"§bVer la invitación de Discord de Hajime.\"},\"clickEvent\":{\"action\":\"suggest_command\",\"value\":\".discord\"}},{\"text\":\".hajime, \",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\"§bVer la versión de Hajime.\"},\"clickEvent\":{\"action\":\"suggest_command\",\"value\":\".hajime\"}},{\"text\":\".a, .ayuda, \",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\"§bVer este mensaje de ayuda.\"},\"clickEvent\":{\"action\":\"suggest_command\",\"value\":\".ayuda\"}},{\"text\":\".nombre, \",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\"§bVer el nombre de este servidor en Hajime.\"},\"clickEvent\":{\"action\":\"suggest_command\",\"value\":\".nombre\"}},{\"text\":\".tiempo, \",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\"§bVer el tiempo local de este servidor.\"},\"clickEvent\":{\"action\":\"suggest_command\",\"value\":\".tiempo\"}},{\"text\":\".tiempofun \",\"hoverEvent\":{\"action\":\"show_text\",\"value\":\"§bVer el tiempo de funcionamiento de este servidor.\"},\"clickEvent\":{\"action\":\"suggest_command\",\"value\":\".tiempofun\"}}]";
server.command.die.regex = ".dado";
server.command.die.output = "§6[Hajime]§f Tiró un dado y consiguió §b";
server.command.coinflip.regex = ".lanzar";
server.command.coinflip.output.heads = "§6[Hajime]§f Lanzó una moneda y consiguió §bcara";
server.command.coinflip.output.tails = "§6[Hajime]§f Lanzó una moneda y consiguió §bcruz";
server.command.discord.regex = ".discord";
server.command.discord.output = "[\"§6[Hajime] §fÚnete el grupo oficial Discord de Hajime en \",{\"text\":\"https://discord.gg/J6asnc3pEG\",\"underlined\":true,\"color\":\"aqua\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https://discord.gg/J6asnc3pEG\"}}]";
server.command.name.regex = ".nombre";
server.command.name.output = "§6[Hajime]§f El nombre de este servidor es §b";
server.command.uptime.regex = ".tiempofun";
server.command.uptime.output1 = "§6[Hajime]§f El tiempo de funcionamiento de este servidor es §b";
server.command.uptime.output2 = "§f minutos (§b";
server.command.uptime.output3 = "§f horas)";
fileServerConfComment = "# Todo que sigue un # es un comentario.";
