help.push_back("\033[1mBem-vindo ao Hajime, o melhor script para a inicialização de servidores de Minecraft!\033[0m");
help.push_back("Esta versão do Hajime foi compilada em " __DATE__ ".");
help.push_back("\033[1m\033[32mUtilização:\033[0m ");
help.push_back(" [as seguintes flags]"); //1 and 2 sandwich a variable
help.push_back("\033[1m-f \033[3marquivo\033[0m ou \033[1m--server-file \033[3marquivo \033[0m\033[1m|\033[0m Especificar um arquivo de configuração do servidor a ser usado manualmente.");
help.push_back("\033[1m-h \033[0mou\033[1m --help |\033[0m Mostrar essa mensagem de ajuda.");
help.push_back("\033[1m-hf \033[1m\033[3marquivo \033[0mou\033[1m --hajime-file\033[0m \033[1m\033[3marquivo \033[0m\033[1m|\033[0m Especificar manualmente o arquivo de configuração utilizado.");
help.push_back("\033[1m-s  \033[0mou\033[1m --install-server \033[1m|\033[0m Criar um arquivo de configuração padrão para o servidor.");
help.push_back("\033[1m-ih \033[1m\033[3marquivo \033[0mou\033[1m --install-hajime-config \033[1m\033[3marquivo \033[0m\033[1m|\033[0m Instalar o arquivo de configuração padrão do Hajime.");
help.push_back("\033[1m-S  \033[0mou\033[1m --install-service \033[1m|\033[0m Instalar um arquivo de inicialização de serviço para que sua plataforma inicie o Hajime automaticamente.");
help.push_back("\033[1m-ss \033[0mou\033[1m --install-servers-file \033[1m|\033[0m Instalar um arquivo de lista de servidores.");
help.push_back("\033[1m-v \033[0mou\033[1m --verbose \033[1m|\033[0m Habilitar logs exageradas.");
help.push_back("\033[1m-i \033[0mou\033[1m --install-hajime \033[1m|\033[0m Execute o assistente de instalação Hajime.");
help.push_back("\033[1m-m \033[0mou\033[1m --monochrome \033[0mor\033[1m --no-colors \033[1m|\033[0m Desabilitar a saída de cores.");
help.push_back("\033[1m-d \033[0mou\033[1m --debug \033[1m|\033[0m Habilitar mensagens de debug.");
help.push_back("\033[1m-l \033[0mou\033[1m --language \033[1m|\033[0m Escolher manualmente o idioma que será usado.");
help.push_back("\033[1m-np \033[0mou\033[1m --no-pauses \033[1m|\033[0m Desabilitar as pausas artificiais.");
help.push_back("\033[1m-tc \033[0mou\033[1m --thread-colors \033[1m|\033[0m Mostrar cores por ID ao invés de tipo de mensagem.");
help.push_back("\033[1m-it \033[0mou\033[1m --show-info-type \033[1m|\033[0m Exibir explicitamente o tipo de informação nas logs.");
help.push_back("\033[1m\033[32mPrecisa de mais ajuda?\033[0m Junte-se ao nosso servidor do Discord em https://discord.gg/J6asnc3pEG");
errnoNotPermitted = "Não permitido. O dispositivo está certo?";
errnoNoFileOrDir = "Não existe tal arquivo ou diretório.";
errnoPermissionDenied = "Permissão negada. O Hajime está sendo administrado pelo root?";
errnoInOut = "Erro de entrada/saída. O disco está bem?";
errnoMemory = "Não há memória suficiente. Será que falta memória?";
errnoUnavailable = "Recurso indisponível.";
errnoAddress = "Endereço inadequado.";
errnoBlockDev = "Não é um aparelho de blocos. Você se certificou de estar montando um dispositivo de armazenamento em massa?";
errnoBusy = "Ocupado. O dispositivo está sendo acessado neste momento?";
errnoDirectory = "É um diretório. Você se certificou de que está montando um dispositivo de armazenamento em massa?";
errnoBadArgs = "Argumentos errados. A configuração está definida corretamente?";
errnoUnknownDev = "Dispositivo desconhecido. O sistema de arquivos é suportado?";
errnoUnknownGeneric = "Erro desconhecido.";
prefixInfo = "*";
prefixError = "X";
prefixWarning = "!";
prefixDebug = "+";
prefixVInfo = "Info";
prefixVError = "Erro";
prefixVWarning = "Aviso";
prefixVDebug = "Debug";
prefixVQuestion = "Pergunta";
prefixQuestion = "?";
errorNotEnoughArgs = "Não foram fornecidos argumentos suficientes";
errorConfDoesNotExist1 = "Arquivo de configuração ";
errorConfDoesNotExist2 = " não existe!";
errorNoHajimeConfig = "Arquivo de configuração padrão do Hajime não encontrado.";
errorStartupServiceWindowsAdmin = "Você precisa executar a Hajime como administrador para instalar o serviço de inicialização.";
errorSystemdRoot = "Você precisa ser o usuário root para instalar o serviço systemd.";
errorNoSystemd = "Parece que não há systemd; em vez disso, use outra opção de instalação.";
errorServersFilePresent = "Arquivo de servidores já existe!";
errorServerFileNotPresent1 = "O arquivo de configuração do servidor (";
errorServerFileNotPresent2 = ") não existe.";
errorServersFileNotCreated = "Arquivo de servidores não foi criado.";
errorCouldntSetPath = "Não foi possível definir o caminho.";
errorGeneric = "Whoops! Ocorreu um erro desconhecido.";
errorMethodNotValid = "O método não é um tipo válido";
errorCreatingDirectory = "Erro ao criar diretório!";
errorFilesInPath = "Há arquivos no caminho";
errorNoServersFile = "Nenhum arquivo de servidor encontrado";
errorMount = "Ocorreu um erro, mas o roteiro vai continuar tentando montar. Erro: ";
errorCode = "Código de erro: ";
errorHajFileNotMade = "Arquivo de configuração do Hajime não foi criado";
errorServerConfNotCreated = "Arquivo de configuração do servidor não foi criado";
errorOptionNotAvailable = "Desculpe, essa opção ainda não está disponível.";
errorInvalidServerNumber = "Número de servidor inválido";
errorServerSelectionInvalid = "Seleção do servidor inválida";
errorDoesntSupportWindows = "O Windows não suporta esta função.";
errorInvalidCommand = "Comando inválido; lista de comandos válidos:";
errorInvalidHajCommand1 = "term, t [servidor] | anexar ao servidor";
errorInvalidServerCommand1 = ".d - detach from server";
warningFoundSysvinitService = "O serviço sysVinit instalado foi encontrado.";
warningFoundSystemdService = "O serviço systemd instalado foi encontrado.";
warningIsRunningFalse = "isRunning está desativado.";
warningTestingWindowsSupport = "Testando o suporte a Windows!";
warningLaunchdServPresent = "Encontrei um serviço de launchd existente.";
warningFoundServerConf = "Encontrei um arquivo de configuração de servidor existente.";
warningFoundServerConfPlusFile = "Encontrei um arquivo de servidor existente chamado ";
warningFoundHajConf = "O arquivo de configuração do Hajime já se encontra disponível";
questionMakeLaunchdServ = "Você gostaria de fazer um novo mesmo assim?";
questionPrompt = "[s/n]";
questionMakeHajimeConfig = "Você gostaria de fazer o arquivo de configuração para o Hajime?";
questionMakeServerConfig = "Você gostaria de criar um novo arquivo de configuração mesmo assim?";
questionMakeNewSysvinitService = "Você gostaria de instalar um novo serviço sysVinit?";
questionWizardServersFile = "Você deseja instalá-lo agora?";
questionWizardServerFile = "Você deseja fazer um arquivo de servidor agora?";
questionWizardStartupService = "Você deseja instalar um serviço de inicialização?";
questionSysvinitUser = "Por favor, digite o USUÁRIO sob o qual você quer que a Hajime funcione. ";
questionSysvinitGroup = "Favor digite o GRUPO do usuário que você inseriu. ";
questionDoSetupInstaller = "Parece que é a primeira vez que você usa o Hajime. Você deseja executar o instalador?";
questionStartHajime = "Você quer iniciar o Hajime agora? Digite \"n\" para sair.";
questionUseFlags = "Você gostaria de aplicar alguns argumentos java previamente feitos ao seu servidor?";
questionInstallNewOne = "Você quer instalar um novo?";
questionInstallNewOneAgain = "Você quer tentar criar um novamente?";
questionCreateAnotherServerFile = "Você quer criar outro arquivo de servidor?";
questionApplyConfigToServerFile = "Você gostaria de aplicar uma configuração ao arquivo do servidor?";
questionUseDefaultServerFile1 = "Você gostaria de usar o arquivo padrão do servidor (";
questionUseDefaultServerFile2 = ") ou alguma outra coisa?";
questionEnterNewServerFile = "Digite um novo arquivo de servidor: ";
questionEnterCustomFlags = "Digite aqui suas flags personalizadas: ";
optionMakeServerFileManually = "Digite um arquivo de servidor manualmente";
optionDoManually = "Faça isso manualmente";
optionEnterManually = "Digite manualmente";
optionLetHajimeDeduce = "Deixe o Hajime deduzir para mim [Não implementado]";
optionSkipStep = "Pular esta etapa";
optionUseDefault = "Utilizar o padrão";
optionChooseOptionBelow = "Escolha uma das opções abaixo.";
optionYourChoice = "Sua escolha: ";
optionAttendedInstallation = "Fazer uma instalação acompanhada";
optionUnattendedInstallation = "Fazer uma instalação desacompanhada";
optionSkipSetup = "Pular setup";
optionAikarFlags = "Utilizar as flags de Aikar";
optionHillttyFlags = "Utilizar as flags de Hilltty";
optionFroggeMCFlags = "Utilizar as flags de FroggeMC com ZGC";
optionBasicZGCFlags = "Utilizar as flags básicas de ZGC";
optionCustomFlags = "Utilizar flags customizadas";
infoInstallingSysvinit = "Instalando o serviço sysVinit";
infoInstallingNewSysvinit = "Instalando o novo serviço sysVinit";
infoInstalledSysvinit = "Serviço sysVinit instalado em /etc/init.d/hajime.sh";
infoCreatedServerConfig1 = "O arquivo de configuração (";
infoCreatedServerConfig2 = ") foi criado";
infoAbortedSysvinit = "Abortar a instalação do serviço sysVinit";
infoNoLogFile = "Nenhum arquivo de log será feito; enviando mensagens para o console.";
infoReadingServerSettings = "Lendo as configurações do servidor...";
infoServerFile = "Arquivo do servidor: ";
infoServerPath = "Caminho do servidor: ";
infoServerCommand = "Comando do servidor: ";
infoServerMethod =  "Método de inicialização do servidor: ";
infoServerDevice = "Dispositivo: ";
infoServerDebug = "Valor de debug: ";
infoServerIsRunning = "O programa está funcionando!";
infoTryingToStartProgram = "Tentando iniciar o programa";
infoStartingServer = "Iniciando o servidor!";
infoServerStartCompleted = "Início do programa concluído";
infoPOSIXdriveMount = "A montagem do disco só é necessária em sistemas POSIX";
infoTryingFilesystem1 = "Tentando o sistema de arquivos ";
infoTryingFilesystem2 = "";
infoTryingMount = "Tentando montar";
infoCreatingDirectory = "Fazendo um novo diretório";
infoNoMount = "Nenhum dispositivo solicitado; nenhuma montagem dessa vez!";
infoDeviceMounted = "Dispositivo montado!";
infoWizardHajimeFile = "Vamos começar com a criação do arquivo que o Hajime utilizará para suas configurações básicas.";
infoWizardServersFile = "Agora, precisaremos estabelecer o \"arquivo de servidores\", ou onde o Hajime procura por servidores para iniciar.";
infoWizardServerFile = "Agora precisamos de um arquivo de servidor para definir um de seus servidores a ser executado.";
infoWizardStartupService = "Por último, precisamos fazer com que o Hajime inicie na inicialização do host.";
infoWizardComplete = "Instalação completa!";
infoWizardNextStepServerFile1 = "Próximos Passos: Digite as configurações de seu servidor em ";
infoWizardNextStepServerFile2 = ".";
infoInstallingDefServConf = "Instalando o arquivo de configuração padrão do servidor em ";
infoInstallingNewServConf = "Instalação de um novo arquivo de configuração de servidor chamado ";
infoInstallingDefHajConf = "Instalando o arquivo de configuração padrão do Hajime ";
infoCheckingExistingFile = "Procurando por um arquivo existente...";
infoHajConfigMade1 = "Arquivo de configuração do Hajime (";
infoHajConfigMade2 = ") feito!";
infoInstallingWStartServ = "Instalando o serviço de inicialização do Windows";
infoTipAdministrator = "Dica: Clique com o botão direito do mouse no ícone do terminal e depois clique em \"Executar como Administrador\"";
infoInstallingLaunchdServ = "Instalando o serviço launchd";
infoInstallingNewLaunchdServ = "Instalando o novo serviço launchd";
infoInstalledLaunchServ = "Serviço sysVinit instalado";
infoAbortedLaunchServ = "Instalação do serviço de inicialização abortado";
infoInstallingServersFile = "Instalando o arquivo padrão de servidores em ";
infoCheckingExistingServersFile = "Procurando por um arquivo existente...";
infoMadeServersFile = "Arquivo de servidores feito!";
infoMakingSystemdServ = "Criando o serviço systemd em ";
infoEnterNewNameForServer1 = "Digite um novo nome para o próximo arquivo de servidor (o anterior foi ";
infoEnterNewNameForServer2 = "): \033[1m";
infoEnterCommand = "Digite um comando...";
debugHajDefConfNoExist1 = "Tentei ler as configurações de ";
debugHajDefConfNoExist2 = " mas elas não existem";
debugReadingReadsettings = "Configurações de leitura em readSettings()";
debugReadReadsettings = "Configurações lidas com sucesso de ";
debugFlagVecInFor = "flagVector[0] no loop For =";
debugFlagVecOutFor = "flagVector[0] fora do loop For  =";
debugUsingOldMethod = "Utilizando o método antigo";
debugUsingNewMethod = "Utilizando o novo método";
debugFlags = "Flags =";
debugFlagArray0 = "flagArray[0] =";
debugFlagArray1 = "flagArray[1] =";
debugValidatingSettings = "Verificando as configurações do servidor";
fileServerConfComment = "# Qualquer coisa depois de um # é um comentário.";
