name: Hajime Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-linux-amd64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          sudo apt update
          sudo apt install -y g++-12 libfmt-dev libboost-all-dev libsensors-dev
          cmake source -D CMAKE_CXX_COMPILER=g++-12
          cmake --build . -j 4
          echo Test passed